<style type="text/css">
body {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
}
table {
  border: 1px solid #000000;
  width: 100%;
  padding: 0px;
  margin: 2px;
}
td {
  font-size: 11px;
  padding: 2px;
  border-right-width: 1px;
  border-bottom-width: 1px;
  border-right-style: solid;
  border-bottom-style: solid;
  border-right-color: #999999;
  border-bottom-color: #999999;
}
thead {
  font-family: Arial, Helvetica, sans-serif;
  font-weight: bold;
  color: #000000;
  background-color: #cccccc;
}
select {
	padding: 1px;
	background-color: #F0F0F0;
	border: 1px solid #999999;
	margin-right: 8px;
	margin-left: 2px;
	margin-bottom: 0px;
	margin-top: 0px;
	font-size: 11px;
}
label {
	font-size: 11px;
	font-weight: bold;
	color: #000033;
}
input {
	padding: 2px;
	border: 1px solid #999999;
	margin-top: 0px;
	margin-right: 8px;
	margin-bottom: 0px;
	margin-left: 2px;
	font-size: 11px;
}
form {
	margin: 0px;
	padding: 0px;
	line-height: 10px;
}
.destaque {color: #FF3300}
.botao {
	color: #000000;
	padding-top: 2px;
	padding-right: 8px;
	padding-bottom: 2px;
	padding-left: 8px;
	background-color: #CCCCCC;
	border: 1px solid #333333;
}
p {
	padding: 0px;
	margin-top: 2px;
	margin-right: 0px;
	margin-bottom: 6px;
	margin-left: 0px;
	line-height: 16px;
}

.titulo_miniatura {font-size: 13px; font-weight: bold; color: #000000;}
.preco_normal {font-size: 12px; color: #666666; text-decoration: line-through;}
.preco_desconto {font-size: 12px; color: #333333;}
.destaque_preco {font-size: 13px; color: #FF3300; font-weight: bold;}
.credito_imagem {font-family: Arial, Helvetica, sans-serif; font-size: 8px; 	color: #666666;	letter-spacing: 1pt;}
</style>
